[directory]
truncate_to_repo = false

[git_status]
modified = '[+$count](green)ğŸ“'
staged = '[++\($count\)](yellow) '
stashed = ""
untracked = '[~$count](purple)ğŸ¤·'
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[deno]
format = "via [ğŸ¦• $version](green bold) "

[sudo]
disabled = false
